version: '3'

services:
  # I used frontend_2 to not conflict to a local container
  frontend_2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3030:3000'
    networks:
      - network_app

networks:
  network_app:
